commit sha short

diff --git a/.github/workflows/android-test-feature-branches.yml b/.github/workflows/android-test-feature-branches.yml
--- a/.github/workflows/android-test-feature-branches.yml
+++ b/.github/workflows/android-test-feature-branches.yml
@@ -53,6 +53,9 @@ jobs:
   set_commit_sha:
     name: Set short git commit SHA
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
     outputs:
       short_sha: ${{ steps.get_sha.outputs.short_sha }}
     steps:
@@ -61,7 +64,13 @@ jobs:
 
       - name: Calculate short commit SHA
         id: get_sha
-        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
+        run: |
+         echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
+         echo "Short commit SHA: ${{ steps.get_sha.outputs.short_sha }}"
+         if [ -z "${{ steps.get_sha.outputs.short_sha }}" ]; then
+           echo "Error: Short commit SHA is empty."
+           exit 1
+         fi
 
   android_tests:
     name: Android Tests
