fix

diff --git a/.github/workflows/android-emulators.yml b/.github/workflows/android-emulators.yml
--- a/.github/workflows/android-emulators.yml
+++ b/.github/workflows/android-emulators.yml
@@ -18,6 +18,12 @@ jobs:
     strategy:
       matrix:
         android-version: [
+          # { api: 24, name: "7" },
+          # { api: 26, name: "8" },
+          # { api: 28, name: "9" },
+          # { api: 29, name: "10" },
+          # { api: 30, name: "11" },
+          # { api: 31, name: "12" },
           { api: 33, name: "13" },
           { api: 34, name: "14" },
           { api: 35, name: "15" }
@@ -94,7 +100,7 @@ jobs:
           fi
           echo "Latest detected build-tools version: $latest_version"
           echo "BUILD_TOOLS_VERSION=$latest_version" >> $GITHUB_ENV
-
+  
       - name: Accept licenses and install SDK components
         timeout-minutes: 15
         run: |
@@ -113,6 +119,7 @@ jobs:
           brew update && brew install qemu
           chmod +x .github/scripts/write_entitlements.sh
           .github/scripts/write_entitlements.sh
+    
 
       - name: Build the project
         run: |
@@ -135,6 +142,7 @@ jobs:
           echo "List of AVDs:"
           echo "$list_avds"
 
+
           memory_size=3072
           if [ ${{ matrix.android-version.api }} -eq 24 ]; then
             memory_size=2048
@@ -146,30 +154,18 @@ jobs:
           $ANDROID_HOME/emulator/emulator \
             -avd test \
             -no-snapshot \
-            -gpu on \
+            -gpu swiftshader_indirect \
             -skin 1440x3120 \
             -memory $memory_size \
             -cores 2 &           
           EMULATOR_PID=$!
           sleep 5
           if ! ps -p $EMULATOR_PID > /dev/null; then
-            echo "Error: Emulator failed to start (PID: $EMULATOR_PID). Trying to start with software acceleration..."
-            $ANDROID_HOME/emulator/emulator \
-              -avd test \
-              -no-snapshot \
-              -gpu swiftshader_indirect \
-              -skin 1440x3120 \
-              -memory $memory_size \
-              -cores 2 &           
-            EMULATOR_PID=$!
-            sleep 5
-            if ! ps -p $EMULATOR_PID > /dev/null; then
-              echo "Error: Emulator failed to start with software acceleration (PID: $EMULATOR_PID)"
-              exit 1
-            fi
+            echo "Error: Emulator failed to start (PID: $EMULATOR_PID)"
+            exit 1
           fi
           echo "Emulator started with PID: $EMULATOR_PID"
-
+          
       - name: Wait for emulator boot completion
         timeout-minutes: 10
         run: |
